descope/react-sdk

LICENSE
README.md
package.json

- Some improvements for the readme files
- License support email 
- Package author and maintenance details

Readme enhancements

---

README.md
examples/app/Login.tsx
examples/app/StepUp.tsx
package-lock.json
package.json
src/components/Descope.tsx
src/types.ts

- Added auto-focus prop to pass to descope web-component
- Expose proper types from descope web-components 
- Some small fixes in readme

fix auto-focus behavior

---

README.md

- Added missing sample app env variables description in readme (DESCOPE_REDIRECT_URL, DESCOPE_TENANT_ID (Thanks @orius123 for noticing 💯 )
- Improved tenant id description
- Simplify sample app env variables table to be more concise, and not to describe the default values that are implemented in the SDK

Reamde fixes and improvements

---

.github/workflows/ci.yml
README.md
src/components/AuthProvider/AuthProvider.tsx
src/hooks/useDescope.ts
src/types.ts
test/hooks/useAuth.test.tsx

fixes: https://github.com/descope/etc/issues/2336

expose entire sdk via useDescope hook

---

rollup.config.js

chore: Build UMD

---

package-lock.json
package.json

fixes https://github.com/descope/react-sdk/issues/291
bump web component to latest version should fix the `PublicKeyCredential`

bump web-component

---

package.json

related: https://github.com/descope/etc/issues/2768

fix: add types to package.json#exports RELEASE

---

package-lock.json
package.json

https://github.com/descope/react-sdk/issues/301
bump web-component

bump web component dependency 

---

package-lock.json
package.json

https://github.com/descope/etc/issues/2853

increase react peer dep version

---

README.md

https://github.com/descope/etc/issues/2859
Add baseUrl example to readme

Add baseUrl example to readme

---

README.md

https://github.com/descope/etc/issues/2883
Fix logout readme to not pass the logout function
will consider changing it back once we solve the issue

Fix logout readme

---

README.md
examples/app/Login.tsx
examples/app/StepUp.tsx
package-lock.json
package.json
src/components/Descope.tsx
src/types.ts
test/components/Descope.test.tsx

https://github.com/descope/etc/issues/290
Need to update web-components version first.
Add translation support

Add translation support

---

package-lock.json
package.json

update Descope Dep and release a version

RELEASE - update Descope dep and release a version

---

package-lock.json
package.json

related https://github.com/descope/etc/issues/3871
https://github.com/descope/descope-js/pull/273
bump web components version

bump web components

---

package-lock.json
package.json

Related PRs
https://github.com/descope/descope-js/pull/260
Description
bump web components version

bump web components version

---

package-lock.json
package.json

flows v2 MAJOR RELEASE

---

package-lock.json
package.json

related https://github.com/descope/etc/issues/4743

bump wc RELEASE

---

package-lock.json
package.json

Fixes [<link_to_github_issue>](https://github.com/descope/etc/issues/4762)

fix issue 4762 RELEASE

---

package-lock.json
package.json

Bump web-component 3.1.3

---

README.md
examples/app/Login.tsx
package-lock.json
package.json
src/components/Descope.tsx
src/types.ts
test/components/Descope.test.tsx

related https://github.com/descope/etc/issues/2954
require: https://github.com/descope/descope-js/pull/329
add form and client keys json to wc

feat: Add form and client custom inputs

---

README.md

related https://github.com/descope/etc/issues/2954
https://github.com/descope/vue-sdk/pull/28
update client form readme

update readme custom inputs 

---

src/types.ts

Change interface to type
this helps TS compiler to infer types in a better way

Change interface to type

---

src/components/Descope.tsx

adding empty setter 
now I remembered why I added it :)

add empty setter for beforeRequest

---

README.md

Add QnA for updating user/session token in backend

Add QnA for updating user/session token in backend

---

examples/app/ManageUsers.tsx
package-lock.json
package.json

Update dependencies and and fix environment variable in ManageUsers component

chore: Update dependencies

---

examples/app/ManageUsers.tsx

small header text fix

---

README.md
examples/app/Login.tsx
package-lock.json
package.json
src/components/Descope.tsx
src/types.ts
test/components/Descope.test.tsx

https://github.com/descope/etc/issues/4136
Descope JS - https://github.com/descope/descope-js/pull/375
Add ready callback

Add ready callback

---

src/constants.ts
src/index.ts
test/components/Descope.test.tsx

allow overriding base headers

---

examples/app/ManageUsers.tsx
package-lock.json
package.json
src/components/UsersManagement.tsx
src/types.ts

- **add widget-id**
- **bump web-component and widget versions**

Add widget-id

---

package-lock.json
package.json

bump UMW RELEASE

---

README.md

readme spacing fix for widgets

readme spacing fix for widgets

---

README.md
src/sdk.ts
test/utilityFunctions.test.ts

https://github.com/descope/etc/issues/6151
Add session and refresh token expiration utilities

feat: Add session and refresh token expiration utilities RELEASE

---

README.md
examples/app/App.tsx
examples/app/Home.tsx
examples/app/ManageAudit.tsx
package-lock.json
package.json
src/components/AuditManagement.tsx
src/index.ts
src/types.ts

https://github.com/descope/etc/issues/4255
Audit widget

Audit widget RELEASE

---

README.md
examples/app/ManageAccessKeys.tsx

https://github.com/descope/etc/issues/4425
https://github.com/descope/etc/issues/3838
Add User Access Key widget to readme

Add User Access Key widget to readme

---

package-lock.json
package.json

Bump web-component 3.11.3 RELEASE

---

package-lock.json
package.json

fix: Bump wc-3.11.5 and RELEASE

---

README.md
examples/app/App.tsx
examples/app/Home.tsx
examples/app/MyUserProfile.tsx
examples/app/Profile.tsx
package-lock.json
package.json
src/components/UserProfile.tsx
src/index.ts
src/types.ts

https://github.com/descope/etc/issues/300
Audit widget

User profile widget RELEASE

---

package-lock.json
package.json

Update packages RELEASE

---

package-lock.json
package.json

Bump web-comopnent 3.11.21 RELEASE

---

README.md
examples/app/index.tsx
package-lock.json
package.json
src/components/AuthProvider/AuthProvider.tsx
src/components/Descope.tsx
src/types.ts

add base static url RELEASE

---

package-lock.json
package.json

Related https://github.com/descope/etc/issues/6618

Bump WebComponent 3.13.0

---

README.md
package-lock.json
package.json
src/components/Descope.tsx
src/types.ts

add validateOnBlur

---

README.md

Fix readme isUserLoading

---

package-lock.json
package.json

Upgrade web-component version to 3.15.3

Upgrade web-component version to 3.15.3 RELEASE

---

src/types.ts

fix callbacks types RELEASE

---

package-lock.json
package.json

bump web component version to include the locale handling.

bump web components version RELEASE

---

README.md
package-lock.json
package.json
src/components/AuthProvider/AuthProvider.tsx
src/components/AuthProvider/useSdk.ts
src/components/Descope.tsx
src/types.ts

Fixes https://github.com/descope/etc/issues/6773

Allow to keep last auth login ID after logout RELEASE

---

package-lock.json
package.json

Fixes https://github.com/descope/react-sdk/issues/531
Bump dependencies that contain the fix of the redundant warn message

bump dependencies 
